name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenxr-dev libvulkan-dev
      - name: Build
        run: zig build
      - name: Test
        run: zig build test
